#!/bin/bash

CHROOT_CMD=''
# if PWD is not /usr/src set chroot cmd
if [ "x${PWD}" != 'x/usr/src' ]; then
	CHROOT_CMD="chroot $(dirname $(dirname ${PWD}))"
fi

# Absence of symlink /usr/src/linux means the system was not initialized
if ! [ -L linux ] ; then
	${CHROOT_CMD} emerge --ask n -1 sys-kernel/gentoo-sources app-arch/xz-utils
	${CHROOT_CMD} eselect kernel set 1
fi

# if file /usr/src/linux/.config does not exist or it differs from /usr/src/kernel_config
if ! diff -rupNq linux/.config kernel_config >/dev/null ; then
	cp kernel_config linux/.config
	# Compile the kernel if it's not yet compiled
	if [ $(find ./linux/ -name '*bzImage*' | wc -l ) == 0 ]; then
		MAKE="${CHROOT_CMD} make -C /usr/src/linux"
		${MAKE} oldconfig
		${MAKE} && ${MAKE} modules_install
		${MAKE} install
	fi
fi
