#!/bin/bash

CHROOT_CMD=''
# if PWD is not / set chroot cmd
if [ "x${PWD}" != 'x/' ]; then
	CHROOT_CMD="chroot ${PWD}"
fi

# Absence of symlink /usr/src/linux means the system was not initialized
if ! [ -L ${PWD%%/}/usr/src/linux ] ; then
	${CHROOT_CMD} emerge --sync
	${CHROOT_CMD} emerge -1 dev-vcs/git sys-kernel/gentoo-sources app-arch/xz-utils
	${CHROOT_CMD} eselect kernel set 1
fi
