#!/bin/bash

CHROOT_CMD=''
# if PWD is not / set chroot cmd
if [ "x${PWD}" != 'x/' ]; then
	CHROOT_CMD="chroot ${PWD}"
fi

# gentoo repo should be git-based but by default it's rsync-based
# so need to fix it and sync other repos as well
if ! [ -d ${PWD%%/}/var/db/repos/gentoo/.git ]; then
	rm -fr ${PWD%%/}/var/db/repos/gentoo
	${CHROOT_CMD} emerge --sync
{{ with $hostname := default .chezmoi.hostname (env "CHEZMOI_HOSTNAME") }}
	[ -f ${PWD%%/}/etc/portage/sets/host_{{ $hostname }} ] && \
		${CHROOT_CMD} emerge -DuN @host_{{ $hostname }}
{{- end }}
fi
